<?php
/*
 * Copyright e107 Inc e107.org, Licensed under GNU GPL (http://www.gnu.org/licenses/gpl.txt)
 *
 * Forum plugin - frontend language file
 *
*/

// MAJOR REWRITE IN PROGRESS BY MOC, DO NOT EDIT THIS FILE UNTIL THIS MESSAGE HAS BEEN REMOVED PLEASE!

/* 
Even though all the forum LAN"s are shared accross the entire plugin, here"s some general direction:
- 0xxx => forum.php
- 1xxx => forum_viewforum.php
- 2xxx => forum_viewtopic.php
- 3xxx => forum_post.php

This is done to offer flexibility when changing or adding in new LAN defines. 

vf, vt, etc. in the comments refer to the LAN defined in the previously separate language files:
vf = viewforum, vt = viewtopic, p = post, etc.
*/

define("e_PAGETITLE", "Форум");

// forum.php (forum_template)
// define("LAN_FORUM_0001", "Forum"); // LAN_46	
define("LAN_FORUM_0002", "Тем"); // LAN_47 / FORLAN_21
define("LAN_FORUM_0003", "Ответов"); // LAN_48 / LAN_55
define("LAN_FORUM_0004", "Последний ответ"); // LAN_49 / FORLAN_22 / LAN_57
define("LAN_FORUM_0005", "Доступ в этот форум разрешен только администраторам"); // LAN_406
define("LAN_FORUM_0006", "Доступ в этот форум разрешен только пользователям"); // LAN_407
define("LAN_FORUM_0007", "Форум только для чтения"); // LAN_408
define("LAN_FORUM_0008", "Доступ в этот форум разрешен для определенного класса"); // LAN_409
define("LAN_FORUM_0009", "Отчет"); // LAN_191 
define("LAN_FORUM_0010", "Рейтинг форума"); // LAN_429
define("LAN_FORUM_0011", "Самые активные темы"); // LAN_430
define("LAN_FORUM_0012", "Мои посты"); // LAN_431
define("LAN_FORUM_0013", "Мои настройки"); // LAN_432
define("LAN_FORUM_0014", "Мой профиль"); // LAN_435
define("LAN_FORUM_0015", "Мои загрузки"); // FORLAN_442
define("LAN_FORUM_0016", "Правила Форума"); // LAN_433// define("FORLAN_165", "Execute functions");
define("LAN_FORUM_0017", "Смотреть статистику форума"); // LAN_441
define("LAN_FORUM_0018", "Добро пожаловать "); // LAN_30
define("LAN_FORUM_0019", "нет новых ответов"); // LAN_31
define("LAN_FORUM_0020", "Есть 1 новый пост "); // LAN_32
define("LAN_FORUM_0021", "Есть"); // LAN_33
define("LAN_FORUM_0022", "новые посты"); // LAN_34
define("LAN_FORUM_0023", "со времени Вашего прошлого визита.");  // LAN_35
define("LAN_FORUM_0024", "Последний раз вы посещали форум ");  // LAN_36
define("LAN_FORUM_0025", "Сегодня");  // LAN_37
//define("LAN_FORUM_0026", ", all times are ");  // LAN_38 
define("LAN_FORUM_0027", "Вы прочитали"); // LAN_196
define("LAN_FORUM_0028", "сообщения(й)."); // LAN_197
define("LAN_FORUM_0029", "Все новые посты прочитаны."); // LAN_198
define("LAN_FORUM_0030", "Отслеживаемые темы"); // LAN_393
define("LAN_FORUM_0031", "Всего пользователи этого форума оставили [x] постов"); // LAN_192 and LAN_404
define("LAN_FORUM_0032", "тема"); // LAN_411
define("LAN_FORUM_0033", "тем"); // LAN_413
define("LAN_FORUM_0034", "ответ"); // LAN_412
define("LAN_FORUM_0035", "ответов"); // LAN_414
define("LAN_FORUM_0036", "Кто в сети: "); // LAN_426
define("LAN_FORUM_0037", "Отобразить полный список"); // LAN_427
define("LAN_FORUM_0038", "(Будет открыто в новом окне)"); // LAN_436
define("LAN_FORUM_0039", "Новые посты"); // LAN_79 // LAN_79 (vf)
define("LAN_FORUM_0040", "Нет новых"); // LAN_80 / LAN_80 (vf)
define("LAN_FORUM_0041", "Закрытый форум"); // LAN_394
//define("LAN_FORUM_0042", "Search"); /// LAN_180 => Generic term, moved to e107_languages/English.php LAN_SEARCH
define("LAN_FORUM_0043", "Вы можете создaть новые темы"); // LAN_204 // FIXME "can / cannot" in bold? 0043-0048
define("LAN_FORUM_0044", "Вы НЕ можете создaвать темы"); // LAN_205
define("LAN_FORUM_0045", "Отвечайте в темах"); // LAN_206
define("LAN_FORUM_0046", "Вы не можете отвечать в темах"); // LAN_207
define("LAN_FORUM_0047", "Редактируйте свои ответы"); // LAN_208
define("LAN_FORUM_0048", "и редактировать свои ответы"); // LAN_209

// FIXME LAN - check if this section (0049 - 0055) could use some LAN optimization
define("LAN_FORUM_0049", "Добро пожаловать, гость"); // LAN_410
define("LAN_FORUM_0050", "Незарегистрированные пользователи могут добавлять и просматривать сообщения, при этом ip-адреса и хосты записываются.<br />Чтобы получить доступ ко всем функциям форумa"); // LAN_44 // FIXME <br />
define("LAN_FORUM_0051", "зарегистрируйтесь"); // LAN_437
define("LAN_FORUM_0052", "и войдите."); // LAN_438
define("LAN_FORUM_0053", "Только зарегистрированные пользователи могут размещать сообщения в этом форуме. Нажмите"); // LAN_45
define("LAN_FORUM_0054", "здесь"); // LAN_438
define("LAN_FORUM_0055", "для авторизации."); // LAN_440

define("LAN_FORUM_0056", "Доступ ограничен"); // LAN_405

define("LAN_FORUM_0057", "Отметить все как прочтенные"); // LAN_199 
define("LAN_FORUM_0058", "Посмотреть новые посты"); // LAN_421

// FIXME LAN - check if this section (0059 - 0064) could use some LAN optimization
define("LAN_FORUM_0059", "пользователь сейчас просматривает форумы"); // LAN_415 / LAN_405 (vf)
define("LAN_FORUM_0060", "пользователей сейчас просматривают форумы"); //LAN_416 / LAN_406 (vf)
define("LAN_FORUM_0061", "пользователь"); // LAN_417 / LAN_407 (vf)
define("LAN_FORUM_0062", "пользователей"); // LAN_419 / LAN_409 (vf)
define("LAN_FORUM_0063", "гость"); // LAN_418 / LAN_408 (vf)
define("LAN_FORUM_0064", "гостей"); // LAN_420 / LAN_410 (vf)

define("LAN_FORUM_0065", "Новые пользователи:"); // LAN_41
define("LAN_FORUM_0066", "Зарегистрировалось пользователей:"); // LAN_42

define("LAN_FORUM_0067", "Пока нет форумов. Пожалуйста, посетите нас позже."); // LAN_51
define("LAN_FORUM_0068", "В этом каталоге нет доступных форумов. Попробуйте в другой раз."); // LAN_52
define("LAN_FORUM_0069", "Подфорумы"); // FORLAN_444 

define("LAN_FORUM_0070", "Остановить отслеживание темы"); // LAN_392 
//define("LAN_FORUM_0071", "Forum Rules"); // LAN_433
define("LAN_FORUM_0072", "Правила не установлены"); // FORLAN_441
define("LAN_FORUM_0073", "Отслеживаемые темы"); // LAN_397
define("LAN_FORUM_0074", "Автор");  // LAN_423
define("LAN_FORUM_0075", "Новые темы"); // LAN_424

// starting at LAN_FORUM_1xxx => forum_viewforum.php
define("LAN_FORUM_1001", "Форумы"); // LAN_01

define("LAN_FORUM_1002", "Подфорум"); // FORLAN_20
define("LAN_FORUM_1003", "Тема"); // LAN_55
define("LAN_FORUM_1004", "Автор"); // LAN_54
define("LAN_FORUM_1005", "Просмотров"); // LAN_56

define("LAN_FORUM_1006", "Важные темы"); // LAN_411 (vf)
define("LAN_FORUM_1007", "Темы"); // LAN_412 (vf)
define("LAN_FORUM_1008", "В этом форуме пока не созданы темы"); // LAN_58
define("LAN_FORUM_1009", "Модератор форума"); // LAN_404
define("LAN_FORUM_1010", "[популярные]"); // LAN_395 (vf)
define("LAN_FORUM_1011", "Прикреплена"); // LAN_202
define("LAN_FORUM_1012", "Прикреплена/Закрыта"); // LAN_203 / 
define("LAN_FORUM_1013", "Объявление"); // LAN_396 // FORLAN_17
define("LAN_FORUM_1014", "Тема закрыта"); // LAN_81 / FORLAN_18
define("LAN_FORUM_1015", "[удалено пользователем]"); // FORLAN_19 (vf)
define("LAN_FORUM_1016", "Опрос"); // FORLAN_23

define("LAN_FORUM_1017", "Перейти"); // LAN_401 (p?)
define("LAN_FORUM_1018", "Новая тема");
// define("LAN_FORUM_1019", "Are you sure?"); // new
define("LAN_FORUM_1020", "Изменить");
define("LAN_FORUM_1021", "Без ответов");

// starting at LAN_FORUM_2xxx => forum_viewtopic.php
define("LAN_FORUM_2001", "Предыдущая"); // LAN_389 
define("LAN_FORUM_2002", "Следующая"); // LAN_390
define("LAN_FORUM_2003", "Модераторы"); // LAN_321
define("LAN_FORUM_2004", "Эта тема закрыта"); // LAN_66
define("LAN_FORUM_2005", "Создать новую тему"); // new
define("LAN_FORUM_2006", "Ответить"); // new
define("LAN_FORUM_2007", "Быстрый ответ"); // new
define("LAN_FORUM_2008", "СКРЫТО - Авторизуйтесь и читайте"); // FORLAN_HIDDEN - used in [hide] bbcode?
define("LAN_FORUM_2009", "Уверены, что хотите удалить эту тему и все посты?"); // LAN_409
define("LAN_FORUM_2010", "Уверены, что хотите удалить этот пост?"); // LAN_410
//define("LAN_FORUM_2011", "posted by"); // LAN_410 // LAN_FORUM_0074
define("LAN_FORUM_2012", "Предыдущей темы не существует"); // LAN_404 (vt)
define("LAN_FORUM_2013", "Нет следующей темы"); // LAN_405 (vt)

define("LAN_FORUM_2015", "Текст"); // LAN_403 (vt)
define("LAN_FORUM_2016", "Правки"); // LAN_29 
define("LAN_FORUM_2017", "автор"); // FORLAN_BY
define("LAN_FORUM_2018", "Сообщение о посте на сайте "); // LAN_422 (vt)
define("LAN_FORUM_2019", "Сообщение от"); // LAN_425 (vt)
define("LAN_FORUM_2020", "Тема форума сообщена"); // LAN_421 (vt)
define("LAN_FORUM_2021", "Сообщение о посте было отправлено"); // LAN_428
define("LAN_FORUM_2022", "Вернуться к форуму"); // LAN_429
define("LAN_FORUM_2023", "Жалоба модератору"); // LAN_414 (vt)
define("LAN_FORUM_2024", "Сообщение о посте в теме"); // LAN_426
define("LAN_FORUM_2025", "Название темы"); // LAN_415
define("LAN_FORUM_2026", "Смотреть пост"); // LAN_420
define("LAN_FORUM_2027", "Вы можете сообщить модератору об этой теме, а также объяснить Ваше нежелание просматривать ее на сайте."); // LAN_417
define("LAN_FORUM_2028", "[НЕ используйте] эту форму для связи с Администрацией по другим причинам."); // LAN_418 - [ and ] are replaced by <b> </b>
define("LAN_FORUM_2029", "Отправить"); // LAN_419 
define("LAN_FORUM_2030", "Вверх"); // LAN_10
define("LAN_FORUM_2031", "Регистрация"); // LAN_06
define("LAN_FORUM_2032", "Постов"); // LAN_67
define("LAN_FORUM_2033", "Визитов на сайт"); // LAN_09
define("LAN_FORUM_2034", "Вебсайт"); // LAN_08
define("LAN_FORUM_2035", "Пользователь"); // LAN_195
define("LAN_FORUM_2036", "Отправить Личное Сообщение"); // new / LAN_399
define("LAN_FORUM_2037", "Пост удален "); // new
define("LAN_FORUM_2038", "Причина"); // new
// define("LAN_FORUM_2039", "Edit"); // LAN_400
// define("LAN_FORUM_2040", "Delete"); // LAN_435 (vf)?
define("LAN_FORUM_2041", "Цитировать"); // LAN_401
define("LAN_FORUM_2042", "Переместить"); // LAN_FORUM_5019 ?
define("LAN_FORUM_2043", "Разделить"); // new
define("LAN_FORUM_2044", "Отправить Email"); // FORLAN_101
define("LAN_FORUM_2045", "Распечатать"); // FORLAN_102
define("LAN_FORUM_2046", "Жалоба модератору"); // LAN_413

// starting at LAN_FORUM_3xxx => forum_post.php 
define("LAN_FORUM_3001", "У вас нет достаточных прав для участия в этом форуме"); // LAN_399 (p)
define("LAN_FORUM_3002", "Эта тема заблокирована"); // LAN_397
define("LAN_FORUM_3003", "Ответов"); // LAN_02 (p)
// define("LAN_FORUM_3004", "Anonymous"); // LAN_311
define("LAN_FORUM_3005", "Предпросмотр"); // LAN_323
define("LAN_FORUM_3006", "Дублированный пост"); // LAN_FORUM_2
define("LAN_FORUM_3007", "Поле(я) не заполнено(ы)"); // LAN_27
define("LAN_FORUM_3008", "Не авторизован"); // LAN_95
define("LAN_FORUM_3009", "Вы не авторизованы для редактирования поста"); //LAN_96
define("LAN_FORUM_3010", "Имя"); // LAN_61
define("LAN_FORUM_3011", "Тема"); // LAN_62
define("LAN_FORUM_3012", "Прикрепить файл/изображение"); // LAN_390
define("LAN_FORUM_3013", "Прикрепить файл"); // LAN_416
define("LAN_FORUM_3014", "Прикрепление файла"); // LAN_392
define("LAN_FORUM_3015", "[Пожалуйста, имейте в виду]"); // LAN_393 1st half - [ and ] are replaced by <b> </b>
define("LAN_FORUM_3016", "Разрешённые файлы"); // LAN_393 2nd half
define("LAN_FORUM_3017", "Любые другие расширения файлов будут немедленно удалены"); // LAN_394
define("LAN_FORUM_3018", "Максимальный размер файла"); // LAN_395
define("LAN_FORUM_3019", "байт"); // LAN_396
define("LAN_FORUM_3020", "Добавить еще вложение"); // LAN_417
define("LAN_FORUM_3021", "Загрузки запрещены: каталог [x] не открыт на запись"); // LAN_FORUM_1 - [x] will be replaced automatically
define("LAN_FORUM_3022", "Последние [y] сообщения"); // LAN_101 and LAN_102 - [y] will be replaced automatically
define("LAN_FORUM_3023", "Обновить тему"); // LAN_77
define("LAN_FORUM_3024", "Обновить ответ"); // LAN_78
define("LAN_FORUM_3025", "Формат данных"); // new
define("LAN_FORUM_3026", "Создать тему как"); // LAN_400 (p)
//define("LAN_FORUM_3027", "Type"); // new -
define("LAN_FORUM_3028", "Добавить опрос"); // new // poll - partly in e107_plugins/poll/poll_class.php
define("LAN_FORUM_3038", "Тема"); // LAN_1
define("LAN_FORUM_3039", "Отключить смайлики в этом посте"); // LAN_FORUMPOST_EMOTES
define("LAN_FORUM_3040", "Включить/выключить email уведомление (отправка email сообщения при ответе на пост)"); // LAN_380
define("LAN_FORUM_3041", "Включить/выключить отслеживание этой темы");
define("LAN_FORUM_3042", "Новая тема/топик");
// missing 41-21

// forum_posted_template
define("LAN_FORUM_3043", "Спасибо"); // LAN_133 (p)
// define("LAN_FORUM_3044", "Click here to return to the forum"); // LAN_326
define("LAN_FORUM_3045", "Опрос успешно добавлен"); // LAN_413
define("LAN_FORUM_3046", "Нажмите для просмотра вашего опроса"); // LAN_414
define("LAN_FORUM_3047", "Ваше сообщение успешно отправлено"); // LAN_324
define("LAN_FORUM_3048", "Щелкните для просмотра вашего сообщения"); // LAN_325
define("LAN_FORUM_3049", "Ваш ответ добавлен"); // LAN_415
define("LAN_FORUM_3050", "Пункт раздела");
define("LAN_FORUM_3051", "Новое местоположение");
define("LAN_FORUM_3052", "Разделить тему");


// forum_icons_template
define("LAN_FORUM_4001", "Есть непрочитанные посты"); // LAN_199 (vf)
define("LAN_FORUM_4002", "Все посты прочитаны"); // new
define("LAN_FORUM_4003", "Новые посты в популярных темах"); // FORLAN_13
define("LAN_FORUM_4004", "Нет постов в популярных темах"); // FORLAN_14
// define("LAN_FORUM_4005", "Website"); // LAN_396
// define("LAN_FORUM_4006", "Email"); // LAN_397
define("LAN_FORUM_4007", "Профиль"); // LAN_398
define("LAN_FORUM_4008", "Личное сообщение"); // LAN_399
define("LAN_FORUM_4009", "Отслеживать тему"); // LAN_391 (vt) 
define("LAN_FORUM_4010", "Не отслеживать тему"); // LAN_392 (vt) / new
define("LAN_FORUM_4011", "Прикрепить тему"); // LAN_401
define("LAN_FORUM_4012", "Открепить тему"); // LAN_398
define("LAN_FORUM_4013", "Заблокировать тему"); // LAN_399
define("LAN_FORUM_4014", "Разблокировать тему"); // LAN_400


// Ajax and actions 
define("LAN_FORUM_CLOSE", "Тема закрыта");
define("LAN_FORUM_OPEN", "Тема открыта");
define("LAN_FORUM_STICK", "Тема прикреплена");
define("LAN_FORUM_UNSTICK", "Тема откреплена");

// Config 
define("LAN_FORUM_5001", "Опрос удален"); // LAN_FORUM_5001
define("LAN_FORUM_5005", "Тема удалена"); // LAN_FORUM_5005
define("LAN_FORUM_5006", "Отмена перемещения"); // LAN_FORUM_5006
define("LAN_FORUM_5007", "Назад к Форумам"); // LAN_FORUM_5007
define("LAN_FORUM_5008", "Настройки Форума"); // LAN_FORUM_5008
define("LAN_FORUM_5009", "Уверены что хотите удалить этот опрос?<br />Если да, то его будет <b><u>не возможно</u></b> восстановить.");
define("LAN_FORUM_5010", "Подтвердить удаление постов"); // LAN_FORUM_5010
define("LAN_FORUM_5019", "Переместить тему"); // LAN_FORUM_5019
define("LAN_FORUM_5021", "перемещена"); // LAN_FORUM_5021
define("LAN_FORUM_5022", "Не менять названия"); // LAN_FORUM_5022
define("LAN_FORUM_5024", "Добавить префикс [x] к названию темы"); // LAN_FORUM_5024
define("LAN_FORUM_5025", "Изменить название"); // LAN_FORUM_5025
define("LAN_FORUM_5026", "Переименовать:"); // LAN_FORUM_5026


// Statistics (lan_forum_stats.php ) ----------------
define("LAN_FORUM_6000", "Общая"); // FSLAN_1
define("LAN_FORUM_6001", "Форум создан"); // LAN_FORUM_6001
define("LAN_FORUM_6002", "Открыт"); // FSLAN_3
define("LAN_FORUM_6003", "Всего постов"); // FSLAN_4
define("LAN_FORUM_6004", "Ответы форума"); // FSLAN_6
define("LAN_FORUM_6005", "Просмотров тем"); // FSLAN_7
define("LAN_FORUM_6006", "Объем тaблицы форумa в БД"); // FSLAN_8
define("LAN_FORUM_6007", "Средняя длина ряда в таблице"); // FSLAN_9
define("LAN_FORUM_6008", "Ранг"); // FSLAN_11
define("LAN_FORUM_6009", "Начал"); // FSLAN_14
define("LAN_FORUM_6010", "Самые просматриваемые темы"); // FSLAN_16
define("LAN_FORUM_6011", "Больше всех создaли тем"); // FSLAN_21
define("LAN_FORUM_6012", "Лучшие ответы"); // FSLAN_22
define("LAN_FORUM_6013", "Статистика Форума"); // FSLAN_23
define("LAN_FORUM_6014", "Среднее кол-во постов в день"); // FSLAN_24

// ---- Uploads ----------

define("LAN_FORUM_7001","Загруженные на форум файлы");
define("LAN_FORUM_7002","Файл удален"); // LAN_FORUM_7002
define("LAN_FORUM_7003","Ошибка: Не удалось удалить файл"); // LAN_FORUM_7003
define("LAN_FORUM_7004","Удаление файла"); // LAN_FORUM_7004
define("LAN_FORUM_7006","Результат"); // LAN_FORUM_7006
define("LAN_FORUM_7007","Найти в теме"); // LAN_FORUM_7007
define("LAN_FORUM_7008","НЕ НАЙДЕНО"); // LAN_FORUM_7008
define("LAN_FORUM_7009","Не найдено загруженных файлов"); // LAN_FORUM_7009

// -------- Tracking Email ------------

define("LAN_FORUM_8001", "Новый пост был добавлен [x] в теме [y] - [z].");
define("LAN_FORUM_8002", "Нажмите на следующую ссылку, чтобы просмотреть запись полностью...");
define("LAN_FORUM_8003", "Включены уведомления по эл. почте для этой темы.");
define("LAN_FORUM_8004", "Уведомления по эл. почте для этой темы отключены.");
define("LAN_FORUM_8005", "В настоящее время Вы отслеживаете эту тему.");
define("LAN_FORUM_8006", "Вы больше не отслеживаете эту тему.");

// -------- View Forum ------------
define("LAN_FORUM_8007", "Прикрепить");
define("LAN_FORUM_8008", "Открепить");
define("LAN_FORUM_8009", "Закрыть");
define("LAN_FORUM_8010", "Открыть");
define("LAN_FORUM_8011", "Отметки состояния");
define("LAN_FORUM_8012", "Видимость");
define("LAN_FORUM_8013", "Опции");

// -------- Forum Post------------
define("LAN_FORUM_8014", "Этот пост и каждый ответ под ним будут перенесены в новую тему");
define("LAN_FORUM_8015", "Внимание!");
define("LAN_FORUM_8016", " (Текущая)");

// -------- Forum Class------------
define("LAN_FORUM_8017", "Возникла ошибка при отключении отслеживания");
define("LAN_FORUM_8018", "Возникла проблема.");
define("LAN_FORUM_8019", "Не удалось удалить тему!");
define("LAN_FORUM_8020", "Тема удалена");
define("LAN_FORUM_8021", "Пост удален");
define("LAN_FORUM_8022", "Не удалось удалить пост");
define("LAN_FORUM_8023", "Не удалось закрыть тему");
define("LAN_FORUM_8024", "Не удалось открыть тему");
define("LAN_FORUM_8025", "Не удалось прикрепить тему");
define("LAN_FORUM_8026", "Не удалось открепить тему");
define("LAN_FORUM_8027", "Не выбрано никаких действий");
define("LAN_FORUM_8028", "Вернуться"); 
define("LAN_FORUM_8029", "Создана новая тема!");
define("LAN_FORUM_8030", "Пост не удален (необходимы права модератора)");

?>